### ISSUE TITLE
Had to remove type: module into package.json

### ISSUE THREAD

**Issue by Wapaca** [wharfkit/web-renderer#105]
Hello,

While trying to integrate wharfkit on nuxt 3 i had to remove type: module into the package.json otherwise i would get "exports is not defined in ES module scope" 

https://github.com/Wapaca/demo-nuxtv3_wharfkit

**Comment by aaroncox** [comment]
I'm able to reproduce this, and checking with the team as to why it's happening. It seems to only happen with nuxt/nextjs, and probably has something to do with their loader. I'll update once we have a resolution!

**Comment by aaroncox** [comment]
This should be resolved as of version 0.5.3 👍
