### ISSUE TITLE
Login with anchor QR code is chopped off

### ISSUE THREAD

**Issue by DenisCarriere** [wharfkit/web-renderer#125]
Browser & OS:
- Firefox/Linux with 4k monitor, zoomed
- URL: https://dev.bounties.pomelo.io/checkout/bdefb4ed32e2 (must be logged in)

Click Payment Method => Connect EOS Wallet

On my Laptop there's no CSS issue, so it's hard to replicate

But apparently on 4K monitors, it's an issue 😅️️

![image](https://github.com/wharfkit/wallet-plugin-anchor/assets/550895/f386f83d-eb99-4a3d-a150-a8933eba67cf)

**Comment by david-at-greymass** [comment]
Fix pr: https://github.com/wharfkit/web-renderer/pull/126
