### ISSUE TITLE
Issue with hardcoded base rem unit in styling

### ISSUE THREAD

**Issue by mvdschee** [wharfkit/web-renderer#138]
<img width="1452" alt="Screenshot 2023-11-23 at 08 52 09" src="https://github.com/wharfkit/web-renderer/assets/26795741/f2fb2f82-4bb2-4b99-8e6a-7f264de76717">

We (NeftyBlocks) are trying to move to the new login flow with Wharfkit, but we are running into an issue with the `--space-m` relying on `1rem`. We have in our HTML exceptions to scale the rem for mobile and tablet for a better reading experience, but for us, `1.6rem ≈ 16px`, all scaling is wrong.

It would be helpful to have an overwrite option `--space-m: var(--wharfkit-space-m, 1rem);` so we can change the default to match our scaling and not have it look broken or used to redo our app styling.

**Comment by aaroncox** [comment]
That's strange, I thought we actually had it so that the parent CSS wouldn't impact the CSS within this shadow dom element 🤔 

We'll take a look at this and as well as at PR #139.

Thanks for both of these!

**Comment by mvdschee** [comment]
Yeah that was the big selling point, but not sure if this is a problem because of `rem` relaying on a `window.document` (html element) and it can't find it in the shadow dom so it will try to use the from the page itself.

**Comment by deansallinen** [comment]
It looks like the QR code issue in the screenshot is separate from the font scaling issue, but I think I got that fixed now. Thanks for the PR! I'll merge it in with a slight name change on the custom property, and add another one in for font size.

**Comment by aaroncox** [comment]
Apologies for the delay in the release, this is now published as 1.1.2.
