### ISSUE TITLE
V1.1.2 doesn't contain new style overwrite

### ISSUE THREAD

**Issue by mvdschee** [wharfkit/web-renderer#141]
In the latest version of the `web-renderer` package, the new overwrite `--wharfkit-space-base` is not included in the compiled code.

![Screenshot 2024-01-06 at 15 21 09](https://github.com/wharfkit/web-renderer/assets/26795741/7f5e8e54-19c3-4329-8b9c-66d19710a371)
![Screenshot 2024-01-06 at 15 20 24](https://github.com/wharfkit/web-renderer/assets/26795741/e3d0aa97-3a57-4aff-84b3-885912fad295)

**Comment by aaroncox** [comment]
Alright, we found the problem. There was a bug in the nodejs version we were using to build the releases, which for whatever reason was stripping that out. We updated the version used to build and this seems to be resolved. 

A new release (1.1.4) has been published and this should be available now. Let us know if it is not or you have any other issues.
