### ISSUE TITLE
In a modal, hitting the escape key does something different than clicking the close button

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/web-renderer#60]
If you use the modal for any purpose and click the close button, the modal closes, and when you perform another action it works.

If you hit escape while any modal is open, the modal closes, but you can no longer open any modal windows.

This can be done with the login prompt. Reproduce:

1. Click Login
2. Hit Escape
3. Click Login

Notice how the login doesn't appear the 2nd time.

**Comment by deansallinen** [comment]
Looks like `escapeClose()` isn't being fired when the escape key is pressed.

**Comment by deansallinen** [comment]
It appears to work when changing `on:keyup|preventDefault...` to `on:keydown...` to keep default keyboard navigation but capture the escape key to run `cancelRequest()`
