### ISSUE TITLE
Animation bug when going forward in screens

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/web-renderer#71]
![animationbug](https://user-images.githubusercontent.com/677686/232964700-e9d06a94-ebdc-4446-9812-76eaefcd699a.gif)

Slack thread related to this: https://greymass.slack.com/archives/C045MUS6F0F/p1681877208229069

Some kind of animation issue causing a white border flashing across the bottom. From what I've seen, it only happens when going forward, not backwards.

**Comment by deansallinen** [comment]
Bug appears to be a brief flash of a horizontal scrollbar as the next screen's content is rendered off-screen to the right. Fixed by setting `overflow: hidden`
