### ISSUE TITLE
The `target="_blank"` causes a new tab to open on Windows when logging in with Anchor

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/web-renderer#88]
https://github.com/wharfkit/web-renderer/blob/f28a98ac8951d014cf28cbdd069b3e2d558797d4/src/ui/components/Link.svelte#L14

I don't think we want the `target="_blank"` for these link elements, at least for the Anchor plugin (and maybe everything?).

Was there a particular reason this was added in, for some specific use case? I'm wondering whether we remove it all together or make it an opt-in to control what that value is. By default I think it shouldn't be there, but am open to the conversation.

**Comment by deansallinen** [comment]
Yeah it's a better UX for the Anchor plugin to not have `target="_blank"` so we should definitely make it either opt-in or opt-out.

I think the idea here was to prevent hijacking the current page and losing state if the prompt included an external link (like, "more information" or "view on block explorer" or something). 

I think whichever we choose depends on which use-case is more common.

**Comment by shaqk** [comment]
I think it has to be removed for all ESR links.
On Firefox, it leaves an empty tab open after login, and you have to switch back to the original dApp tab.

On other browsers, its still a bad UX as it feels like Ads trying to open new tabs, even though it closes the tab after.

**Comment by deansallinen** [comment]
Thanks for the feedback @shaqk! Default in 0.4.2 is now to open links in the same tab, and you can pass `target: "_blank"` through `data` on the `Link` component to open in a new tab, e.g. for the link to the Wharfkit.com homepage.
