### ISSUE TITLE
Countdown spacing

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/web-renderer#95]
When providing a label and countdown to the new countdown element, it seems to be overflowing out of its container and overlapping the button. 

Need to add some clearance there so its not overlapping the button.

<img width="433" alt="image" src="https://github.com/wharfkit/web-renderer/assets/677686/a3b80850-3fb5-47e2-a9c7-d083ee8f8672">

**Comment by deansallinen** [comment]
Removing fixed height in #96 allows the countdown component to be correctly spaced.
